//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceHelth.Model.Resources.ExpertsProfiles
{ 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpertsProfiles
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpertsProfiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourceHelth.Model.Resources.ExpertsProfiles.ExpertsProfiles", typeof(ExpertsProfiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty ID.
        /// </summary>
        public static string ImageUrl
        {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        public static string LinkedInUrl
        {
            get
            {
                return ResourceManager.GetString("LinkedInUrl", resourceCulture);
            }
        }
        public static string YouToubeUrl
        {
            get
            {
                return ResourceManager.GetString("YouToubeUrl", resourceCulture);
            }
        }
        public static string InstagramUrl
        {
            get
            {
                return ResourceManager.GetString("InstagramUrl", resourceCulture);
            }
        }
        public static string Names
        {
            get
            {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        public static string Summary
        {
            get
            {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        public static string Education
        {
            get
            {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        public static string Experiences
        {
            get
            {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        public static string Certificates
        {
            get
            {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        public static string Languages
        {
            get
            {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        public static string NamePromptEn
        {
            get
            {
                return ResourceManager.GetString("NamePromptEn", resourceCulture);
            }
        }
        public static string SummaryPromptEn
        {
            get
            {
                return ResourceManager.GetString("SummaryPromptEn", resourceCulture);
            }
        }
        public static string EducationPromptEn
        {
            get
            {
                return ResourceManager.GetString("EducationPromptEn", resourceCulture);
            }
        }
        public static string ExperiencesPromptEn
        {
            get
            {
                return ResourceManager.GetString("ExperiencesPromptEn", resourceCulture);
            }
        }
        public static string CertificatesPromptEn
        {
            get
            {
                return ResourceManager.GetString("CertificatesPromptEn", resourceCulture);
            }
        }
        public static string LanguagesPromptEn
        {
            get
            {
                return ResourceManager.GetString("LanguagesPromptEn", resourceCulture);
            }
        }
        public static string NamePromptAR
        {
            get
            {
                return ResourceManager.GetString("NamePromptAR", resourceCulture);
            }
        }
        public static string SummaryPromptAR
        {
            get
            {
                return ResourceManager.GetString("SummaryPromptAR", resourceCulture);
            }
        }
        public static string EducationPromptAR
        {
            get
            {
                return ResourceManager.GetString("EducationPromptAR", resourceCulture);
            }
        }
        public static string ExperiencesPromptAR
        {
            get
            {
                return ResourceManager.GetString("ExperiencesPromptAR", resourceCulture);
            }
        }
        public static string CertificatesPromptAR
        {
            get
            {
                return ResourceManager.GetString("CertificatesPromptAR", resourceCulture);
            }
        }
        public static string LanguagesPromptAr
        {
            get
            {
                return ResourceManager.GetString("LanguagesPromptAr", resourceCulture);
            }
        }
        public static string Experts
        {
            get
            {
                return ResourceManager.GetString("Experts", resourceCulture);
            }
        }
        public static string DeleteConfirm
        {
            get
            {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        public static string DescriptionEn
        {
            get
            {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        public static string DescriptionAr
        {
            get
            {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        public static string DescriptionPromptAR
        {
            get
            {
                return ResourceManager.GetString("DescriptionPromptAR", resourceCulture);
            }
        }
        public static string DescriptionPromptEn
        {
            get
            {
                return ResourceManager.GetString("DescriptionPromptAR", resourceCulture);
            }
        }
        public static string ViewExpertProfile
        {
            get
            {
                return ResourceManager.GetString("ViewExpertProfile", resourceCulture);
            }
        }
    }
}
