//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceHelth.Model.Resources.Coupons { 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Coupons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Coupons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourceHelth.Model.Resources.Coupons.Coupons", typeof(Coupons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty ID.
        /// </summary>
        public static string CouponCode {
            get {
                return ResourceManager.GetString("CouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string coupon_discount_rate
        {
            get {
                return ResourceManager.GetString("coupon_discount_rate", resourceCulture);
            }
        }
        public static string coupon_stat
        {
            get
            {
                return ResourceManager.GetString("coupon_stat", resourceCulture);
            }
        }
        public static string coupon_satrt_date
        {
            get
            {
                return ResourceManager.GetString("coupon_satrt_date", resourceCulture);
            }
        }
        public static string coupon_end_date
        {
            get
            {
                return ResourceManager.GetString("coupon_end_date", resourceCulture);
            }
        }

        public static string coupon_created_at
        {
            get
            {
                return ResourceManager.GetString("coupon_created_at", resourceCulture);
            }
        }
        public static string coupon_for
        {
            get
            {
                return ResourceManager.GetString("coupon_for", resourceCulture);
            }
        }

        public static string ActiveCoupon
        {
            get
            {
                return ResourceManager.GetString("ActiveCoupon", resourceCulture);
            }
        }

        public static string InActiveCoupon
        {
            get
            {
                return ResourceManager.GetString("InActiveCoupon", resourceCulture);
            }
        }
        public static string CouponStatPrompt
        {
            get
            {
                return ResourceManager.GetString("CouponStatPrompt", resourceCulture);
            }
        }
        public static string CouponForPromptDD
        {
            get
            {
                return ResourceManager.GetString("CouponForPromptDD", resourceCulture);
            }
        }
        public static string CouponForPromptDDO1
        {
            get
            {
                return ResourceManager.GetString("CouponForPromptDDO1", resourceCulture);
            }
        }
        public static string CouponForPromptDDO4
        {
            get
            {
                return ResourceManager.GetString("CouponForPromptDDO4", resourceCulture);
            }
        }
        public static string CouponForPromptDDO2
        {
            get
            {
                return ResourceManager.GetString("CouponForPromptDDO2", resourceCulture);
            }
        }
        public static string CouponForPromptDDO3
        {
            get
            {
                return ResourceManager.GetString("CouponForPromptDDO3", resourceCulture);
            }
        }
        public static string AddCouponButton
        {
            get
            {
                return ResourceManager.GetString("AddCoupon", resourceCulture);
            }
        }

        public static string ShowAllList
        {
            get
            {
                return ResourceManager.GetString("ShowAllList", resourceCulture);
            }
        }

        public static string BackToList
        {
            get
            {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }

        public static string CouponCodePrompt
        {
            get
            {
                return ResourceManager.GetString("CouponCodePrompt", resourceCulture);
            }
        }

        public static string CouponDiscountRatePrompt
        {
            get
            {
                return ResourceManager.GetString("CouponDiscountRatePrompt", resourceCulture);
            }
        }
        public static string CouponForPrompt
        {
            get
            {
                return ResourceManager.GetString("CouponForPrompt", resourceCulture);
            }
        }
        public static string CouponListEdit
        {
            get
            {
                return ResourceManager.GetString("CouponListEdit", resourceCulture);
            }
        }
        public static string CouponListDelete
        {
            get
            {
                return ResourceManager.GetString("CouponListDelete", resourceCulture);
            }
        }

        public static string SaveCoupon
        {
            get
            {
                return ResourceManager.GetString("SaveCoupon", resourceCulture);
            }
        }
        public static string DeleteCoupon
        {
            get
            {
                return ResourceManager.GetString("DeleteCoupon", resourceCulture);
            }
        }
    }
}
