//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceHelth.Model.Resources.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Courses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Courses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourceHelth.Model.Resources.Courses.Courses", typeof(Courses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseDate.
        /// </summary>
        public static string CourseDate {
            get {
                return ResourceManager.GetString("CourseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseID.
        /// </summary>
        public static string CourseID {
            get {
                return ResourceManager.GetString("CourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseName.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoursePrice.
        /// </summary>
        public static string CoursePrice {
            get {
                return ResourceManager.GetString("CoursePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseType.
        /// </summary>
        public static string CourseType {
            get {
                return ResourceManager.GetString("CourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentID.
        /// </summary>
        public static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntroText.
        /// </summary>
        public static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntroVideo.
        /// </summary>
        public static string IntroVideo {
            get {
                return ResourceManager.GetString("IntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isfree.
        /// </summary>
        public static string isfree {
            get {
                return ResourceManager.GetString("isfree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainerID.
        /// </summary>
        public static string TrainerID {
            get {
                return ResourceManager.GetString("TrainerID", resourceCulture);
            }
        }
    }
}
