//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Introducing Video.
        /// </summary>
        internal static string AddIntroVideo {
            get {
                return ResourceManager.GetString("AddIntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        internal static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book an appointment.
        /// </summary>
        internal static string BookAnAppointment {
            get {
                return ResourceManager.GetString("BookAnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Your Document.
        /// </summary>
        internal static string BuildYourDocument {
            get {
                return ResourceManager.GetString("BuildYourDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up you accept our.
        /// </summary>
        internal static string BySigningUpYouAcceptOur {
            get {
                return ResourceManager.GetString("BySigningUpYouAcceptOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Logo.
        /// </summary>
        internal static string ChooseLogo {
            get {
                return ResourceManager.GetString("ChooseLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company / Org Name.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Miles Profile.
        /// </summary>
        internal static string CompanyProfile {
            get {
                return ResourceManager.GetString("CompanyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult.
        /// </summary>
        internal static string Consult {
            get {
                return ResourceManager.GetString("Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree {
            get {
                return ResourceManager.GetString("Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain.
        /// </summary>
        internal static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide-PDF.
        /// </summary>
        internal static string GuidePDF {
            get {
                return ResourceManager.GetString("GuidePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you found an error.
        /// </summary>
        internal static string HaveYouFoundAnError {
            get {
                return ResourceManager.GetString("HaveYouFoundAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        internal static string HealthCheck {
            get {
                return ResourceManager.GetString("HealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check On Date.
        /// </summary>
        internal static string HealthCheckOnDate {
            get {
                return ResourceManager.GetString("HealthCheckOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy virtual HR expert advices to attend your pressing HR challenges. Subscribe monthly to a capped 10 hours per month. Please write below your specific requirements..
        /// </summary>
        internal static string HRDoctorContent {
            get {
                return ResourceManager.GetString("HRDoctorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree With.
        /// </summary>
        internal static string IAgreeWith {
            get {
                return ResourceManager.GetString("IAgreeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Arabic.
        /// </summary>
        internal static string InArabic {
            get {
                return ResourceManager.GetString("InArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In English.
        /// </summary>
        internal static string InEnglish {
            get {
                return ResourceManager.GetString("InEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing Video Details.
        /// </summary>
        internal static string IntroVideo {
            get {
                return ResourceManager.GetString("IntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Please.
        /// </summary>
        internal static string LoginPlease {
            get {
                return ResourceManager.GetString("LoginPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Registered On ManualBuilder Plan For One Year Successful.
        /// </summary>
        internal static string ManualBuilderAnnualRegisterd {
            get {
                return ResourceManager.GetString("ManualBuilderAnnualRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Registered On ManualBuilder Plan For One Month Successful.
        /// </summary>
        internal static string ManualBuilderMonthlyRegisterd {
            get {
                return ResourceManager.GetString("ManualBuilderMonthlyRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May be.
        /// </summary>
        internal static string Maybe {
            get {
                return ResourceManager.GetString("Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Section.
        /// </summary>
        internal static string NewSection {
            get {
                return ResourceManager.GetString("NewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Employees.
        /// </summary>
        internal static string NumberOfEmployees {
            get {
                return ResourceManager.GetString("NumberOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMR.
        /// </summary>
        internal static string OMR {
            get {
                return ResourceManager.GetString("OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Here.
        /// </summary>
        internal static string OrderHere {
            get {
                return ResourceManager.GetString("OrderHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Miss-Match.
        /// </summary>
        internal static string PasswordMissmatch {
            get {
                return ResourceManager.GetString("PasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Month.
        /// </summary>
        internal static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Year.
        /// </summary>
        internal static string PerYear {
            get {
                return ResourceManager.GetString("PerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Checks.
        /// </summary>
        internal static string PreviousChecks {
            get {
                return ResourceManager.GetString("PreviousChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVER MY PASSWORD.
        /// </summary>
        internal static string RecoverMyPassword {
            get {
                return ResourceManager.GetString("RecoverMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Successfully.
        /// </summary>
        internal static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Request Sent To Admin.
        /// </summary>
        internal static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required.
        /// </summary>
        internal static string RequiredCompanyName {
            get {
                return ResourceManager.GetString("RequiredCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name is required.
        /// </summary>
        internal static string RequiredDocumentName {
            get {
                return ResourceManager.GetString("RequiredDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        internal static string RequiredPhone {
            get {
                return ResourceManager.GetString("RequiredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedSuccessffuly.
        /// </summary>
        internal static string SavedSuccessffuly {
            get {
                return ResourceManager.GetString("SavedSuccessffuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Activated.
        /// </summary>
        internal static string SectionActivated {
            get {
                return ResourceManager.GetString("SectionActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Deactivated.
        /// </summary>
        internal static string SectionDeactivated {
            get {
                return ResourceManager.GetString("SectionDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Files.
        /// </summary>
        internal static string SeeFiles {
            get {
                return ResourceManager.GetString("SeeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results.
        /// </summary>
        internal static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START THE DIAGNOSIS.
        /// </summary>
        internal static string StartTheDiagnosis {
            get {
                return ResourceManager.GetString("StartTheDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Registered On StartUp Plan For One Year Successful.
        /// </summary>
        internal static string StartUpAnnualRegisterd {
            get {
                return ResourceManager.GetString("StartUpAnnualRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Registered On StartUp Plan For One Month Successful.
        /// </summary>
        internal static string StartUpMonthlyRegisterd {
            get {
                return ResourceManager.GetString("StartUpMonthlyRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Free.
        /// </summary>
        internal static string SubscribeFree {
            get {
                return ResourceManager.GetString("SubscribeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        internal static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string UpdatedSuccessffuly {
            get {
                return ResourceManager.GetString("UpdatedSuccessffuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
